Repository Lumenaries/lumen, pull requests merged in 2024-04, with the labels that each got.

#14 Create Basic Frontend
  README.md
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/prettier.config.js
  frontend/public/fonts/poppins/black.ttf
  frontend/public/fonts/poppins/bold.ttf
  frontend/public/fonts/poppins/extrabold.ttf
  frontend/public/fonts/poppins/medium.ttf
  frontend/public/fonts/poppins/normal.ttf
  frontend/public/fonts/poppins/semibold.ttf
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/SportCard.tsx
  frontend/src/components/SportIcons.tsx
  frontend/src/components/UtilityComponents.tsx
  frontend/src/components/UtilityIcons.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/pages/Advertisements.tsx
  frontend/src/pages/Games.tsx
  frontend/src/pages/Settings.tsx
  frontend/src/pages/SportConfig.tsx
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/vite.config.ts
  partitions.csv
  sdkconfig.defaults
  src/CMakeLists.txt
  src/Kconfig.projbuild
  src/lumen/web/server.cpp
  src/main.cpp
Labels: frontend, feature

#21 Hotfix Filesystem Function
  src/main.cpp
Labels: bug, backend

#33 Adjust Toggle and Menu Alignment in Header
  frontend/src/components/Header.tsx
Labels: bug, frontend

#34 Create Activity Class
  .clang-format
  src/CMakeLists.txt
  src/lumen/activity/activity.hpp
  src/lumen/activity/context.cpp
  src/lumen/activity/context.hpp
  src/lumen/activity/field/field.hpp
  src/lumen/activity/field/number.cpp
  src/lumen/activity/field/number.hpp
  src/lumen/activity/field/team.cpp
  src/lumen/activity/field/team.hpp
  src/lumen/activity/field/text.cpp
  src/lumen/activity/field/text.hpp
  src/lumen/activity/football.cpp
  src/lumen/activity/football.hpp
  src/lumen/app_task.cpp
  src/lumen/web/server.cpp
  src/lumen/web/server.hpp
Labels: backend

#32 Create Basic Button Functionality
  src/CMakeLists.txt
  src/idf_component.yml
  src/lumen/hardware/button/button.cpp
  src/lumen/hardware/button/button.hpp
  src/lumen/hardware/button/led_button.cpp
  src/lumen/hardware/button/led_button.hpp
  src/lumen/hardware/button/rgb_button.cpp
  src/lumen/hardware/button/rgb_button.hpp
  src/lumen/hardware/button/rocker_switch.cpp
  src/lumen/hardware/button/rocker_switch.hpp
  src/lumen/hardware/led_pin.cpp
  src/lumen/hardware/led_pin.hpp
Labels: backend, feature

#47 Replace the RGB Button with a Dual LED Button
  src/CMakeLists.txt
  src/lumen/hardware/button/rg_led_button.cpp
  src/lumen/hardware/button/rg_led_button.hpp
  src/lumen/hardware/button/rgb_button.cpp
Labels: backend

#49 Create Connect Activity
  src/CMakeLists.txt
  src/Kconfig.projbuild
  src/lumen/activity/activity.hpp
  src/lumen/activity/connect.cpp
  src/lumen/activity/connect.hpp
  src/lumen/activity/context.cpp
  src/lumen/activity/context.hpp
  src/lumen/app_task.cpp
  src/lumen/button_callback.cpp
  src/lumen/button_callback.hpp
  src/lumen/hardware/button/button.cpp
  src/lumen/hardware/button/button.hpp
  src/lumen/net/wifi.cpp
  src/lumen/net/wifi.hpp
  src/main.cpp
Labels: backend

#53 Move Disconnect Functionality to Timer Button
  src/Kconfig.projbuild
  src/lumen/app_task.cpp
  src/lumen/button_callback.cpp
  src/lumen/button_callback.hpp
Labels: backend

#56 Implement Deep Sleep
  README.md
  sdkconfig.defaults
  src/lumen/app_task.cpp
  src/lumen/button_callback.cpp
  src/lumen/button_callback.hpp
  src/lumen/hardware/button/button.cpp
  src/lumen/hardware/button/button.hpp
  src/lumen/hardware/button/rg_led_button.cpp
  src/lumen/hardware/led_pin.cpp
Labels: backend

#58 Remove Dark Mode Support
  .gitignore
  frontend/src/components/Header.tsx
  frontend/src/pages/Settings.tsx
Labels: frontend

#60 Add Fields to Football Activity
  frontend/src/components/ActivityBaseConfig.tsx
  frontend/src/components/ActivityCard.tsx
  frontend/src/components/ActivityField.tsx
  frontend/src/components/ActivityIcons.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/UtilityIcons.tsx
  frontend/src/index.tsx
  frontend/src/pages/Activities.tsx
  frontend/src/pages/Games.tsx
  frontend/src/pages/activityConfig/BaseballConfig.tsx
  frontend/src/pages/activityConfig/BasketballConfig.tsx
  frontend/src/pages/activityConfig/FootballConfig.tsx
  frontend/src/pages/activityConfig/SoccerConfig.tsx
  frontend/src/pages/activityConfig/TennisConfig.tsx
  frontend/src/pages/activityConfig/VolleyballConfig.tsx
Labels: frontend

#62 Integrate Timer Button
  src/lumen/activity/activity.cpp
  src/lumen/activity/activity.hpp
  src/lumen/activity/context.cpp
  src/lumen/activity/context.hpp
  src/lumen/activity/football.cpp
  src/lumen/activity/football.hpp
  src/lumen/app_task.cpp
  src/lumen/button_callback.cpp
  src/lumen/button_callback.hpp
Labels: backend

#64 Integrate Rocker Switches
  src/Kconfig.projbuild
  src/lumen/activity/activity.hpp
  src/lumen/activity/football.cpp
  src/lumen/app_task.cpp
  src/lumen/button_callback.cpp
  src/lumen/button_callback.hpp
Labels: backend, feature

#66 Add LED Indication when Timer Button Pressed
  src/lumen/app_task.cpp
  src/lumen/button_callback.cpp
  src/lumen/button_callback.hpp
Labels: backend

#67 Disable Double-tap to Zoom
  frontend/src/components/ActivityBaseConfig.tsx
  frontend/src/components/ActivityField.tsx
Labels: bug, frontend

#71 Create SD Card Module and Activity Store/Load
  src/CMakeLists.txt
  src/Kconfig.projbuild
  src/lumen/activity/activity.cpp
  src/lumen/activity/activity.hpp
  src/lumen/activity/context.cpp
  src/lumen/activity/context.hpp
  src/lumen/activity/field/number.cpp
  src/lumen/activity/field/number.hpp
  src/lumen/activity/field/timer.cpp
  src/lumen/activity/field/timer.hpp
  src/lumen/activity/football.cpp
  src/lumen/activity/football.hpp
  src/lumen/app_task.cpp
  src/lumen/button_callback.cpp
  src/lumen/hardware/sd_card.cpp
  src/lumen/hardware/sd_card.hpp
  src/main.cpp
Labels: backend, feature

#74 Save Activity State (with Power)
  src/lumen/activity/context.cpp
  src/lumen/activity/context.hpp
  src/lumen/web/server.cpp
Labels: backend

#78 Switch to Football Activity & GET State
  frontend/src/components/ActivityBaseConfig.tsx
  frontend/src/components/ActivityField.tsx
  frontend/src/pages/Activities.tsx
  frontend/src/pages/activityConfig/FootballConfig.tsx
  src/lumen/activity/context.cpp
  src/lumen/activity/context.hpp
  src/lumen/activity/field/number.cpp
  src/lumen/activity/field/number.hpp
  src/lumen/web/handler/football.cpp
  src/lumen/web/handler/football.hpp
  src/lumen/web/server.cpp
Labels: web server, feature

#82 Remove Menu Icon
  frontend/src/components/Header.tsx
  frontend/src/components/UtilityIcons.tsx
Labels: frontend

#85 Change Team Names
  frontend/src/components/ActivityBaseConfig.tsx
  frontend/src/pages/Settings.tsx
  frontend/src/pages/activityConfig/FootballConfig.tsx
  src/lumen/web/handler/football.cpp
Labels: frontend, web server, feature

#93 Play Timer Alarm
  frontend/public/audio/timerAlarm.mp3
  frontend/src/components/ActivityBaseConfig.tsx
Labels: frontend
